
title: lakshman's blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://blog.lakshmanbasnet.com

permalink: pretty
permalink: /:categories/:title

email: 
description: Computer Science Student, Tech Enthusiast and Occasional Blogger from Nepal - Laxman Basnet | Lakshman's Blog
des: Life, Travel & Technology Blogs by lakshman from Nepal
collections:
  photo-gallery: 
    output: true
 

gems:
- jekyll-seo-tag
- jekyll-admin
- jekyll-paginate

sass:
  style: compressed

paginate: 12
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: []





